import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "../components/navigation";

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className="flex flex-col items-center">
          <div className="max-w-[500px] min-h-screen w-full h-full">
            <Navigation />
            <main className="flex flex-col justify-center items-center">
              {children}
            </main>
            <footer className="fixed bottom-0">
              <p>© 2024 My Mobile Web Page</p>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
